name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-14
    environment: default
    steps:
      - uses: actions/checkout@v3
      - name: SwiftFormat version
        run: swiftformat --version
      - name: Format lint
        run: swiftformat --lint .
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: SwiftLint version
        run: swiftlint --version
      - name: Lint
        run: swiftlint lint --quiet
  macos-test:
    runs-on: macos-14
    environment: default
    strategy:
      matrix:
        xcode: ['15.2']
        # Swift: 5.9.2
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run Tests
        run: TEMP_DIR=${{ runner.temp }} swift test --enable-code-coverage
  linux-test:
    runs-on: ubuntu-latest
    environment: default
    
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: TEMP_DIR=${{ runner.temp }} swift test
  windows-test:
    runs-on: windows-latest
    environment: default
    
    steps:
      - uses: actions/checkout@v3
      - name: Install Swift
        run: winget install --id Swift.Toolchain -e
      - name: Run Tests
        run: TEMP_DIR=${{ runner.temp }} swift test
